[tool.poetry]
name = "app"
version = "0.1.0"
description = "Video LLM-based search engine"
authors = ["MichalPysik <n3r0x541@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.115.2"
uvicorn = "^0.32.0"
pillow = "^11.0.0"
torch = "^2.5.1"
torchvision = "^0.20.1"
pydantic = "^2.10.3"
transformers = "^4.47.0"
python-dotenv = "^1.0.1"
opencv-python = "^4.10.0.84"
pymilvus = "^2.5.0"


[tool.poetry.group.dev.dependencies]
black = "^24.10.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
